version: '3.8'
services:
  backend:
    build: ./
    ports:
      - "3000:3000"
    environment:
      - DB_HOST=db
      - DB_PORT=5432
      - DB_USERNAME=test
      - DB_PASSWORD=test
      - DB_NAME=hiringapp
    depends_on:
      - db
  db:
    image: postgres
    ports:
      - "5432:5432"
    environment:
      - POSTGRES_DB=hiringapp
      - POSTGRES_USER=test # TODO: Get those from environment variables
      - POSTGRES_PASSWORD=test # TODO: Get those from environment variables
    volumes:
      - postgres_data:/var/lib/postgresql/data

volumes:
  postgres_data:
